"""HTML report of a DoE: methodology, quality, results, anomalies and recommendations.

Two output modes:

- **folder** (default, ``self_contained=False``): writes ``<output_dir>/index.html``
  plus ``report.css``, ``images/*.png`` and ``data/*.csv`` — portable assets a
  researcher can reuse.
- **self-contained** (``self_contained=True``): a single ``.html`` with inlined CSS
  and base64 plots — trivially emailable.

The report is **bilingual** (``lang="en"`` default, ``lang="es"``). The narrative is
**rule-based** (deterministic, no LLM), so it is reproducible and offline.

Usage::

    import doekit as ed
    ed.report(design, response=y)                          # folder ./report/
    ed.report(design, response=y, self_contained=True)     # single .html
    ed.report(design, response=y, lang="es")               # Spanish
    ed.fit_linear_model(design, y, report="report/")       # as an argument
    ed.evaluate(design, report=True)                       # True -> ./report/

Requires ``matplotlib`` (extra ``[report]``).
"""

from __future__ import annotations

import base64
import io
import webbrowser
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from . import __version__
from .analysis import fit_linear_model
from .evaluate import evaluate as _evaluate
from .model import Model, Interaction, Power
from .designs.base import Design

_DEFAULT_THRESHOLDS = {"d_excellent": 90.0, "d_ok": 70.0, "power_target": 0.8, "vif_warn": 5.0}

_ASSETS = Path(__file__).parent / "assets"


# --- internationalized strings ----------------------------------------------
#
# Every user-facing string of the report lives here, keyed by language. English
# is the source language; ``es`` is the translation. ``_t(lang, key)`` falls back
# to English for any missing key.

_STRINGS = {
    "en": {
        "title_default": "DoE report — {kind}",
        "sub": "Generated {now} · doekit {ver} · {runs} runs, {params} params, dof={dof}",
        "h_exec": "Executive summary",
        "recommendation": "Recommendation",
        "h_method": "Methodology",
        "h_factors": "Factors",
        "th_factor": "Factor", "th_type": "Type", "th_range": "Range / levels",
        "coded": "coded", "model": "Model",
        "see_matrix": "View design matrix ({runs} runs)",
        "h_quality": "Design quality",
        "rank_deficient_q": "<b>Saturated/supersaturated design:</b> it cannot estimate "
                            "the model; efficiencies are undefined.",
        "card_d": "D-efficiency", "card_a": "A-efficiency", "card_g": "G-efficiency",
        "gloss_eff": "D-efficiency measures the overall information of the estimates "
                     "(100% = orthogonal); G, the worst prediction variance in the region. "
                     "&ge;90% excellent, 70-90% acceptable, &lt;70% review.",
        "gloss_fds": "FDS: fraction of the region (x-axis) vs. scaled prediction variance "
                     "(y-axis). A low, flat curve = uniform prediction.",
        "h_power": "Power by term",
        "gloss_power": "Probability of detecting an effect of the anticipated size. "
                       "Target &ge;{target:.0%}.",
        "vif_max": "Max VIF", "vif_gloss": "(1 = orthogonal; &gt;5 indicates multicollinearity).",
        "h_alias": "Alias matrix",
        "gloss_alias": "Coefficient bias from omitted terms (two-factor interactions). "
                       "Intense cells = strong confounding.",
        "h_results": "Analysis results",
        "results_line": "R&sup2; = {r2:.4f} · adjusted R&sup2; = {r2adj:.4f} · "
                        "sigma&sup2; = {s2:.4g} · dof = {dof}",
        "gloss_sig": "Significance: *** p&lt;0.001, ** p&lt;0.01, * p&lt;0.05, . p&lt;0.1",
        "h_anom": "Anomalous values",
        "no_anom": "No atypical or influential runs detected.",
        "gloss_anom": "outlier: |studentized residual|&gt;3 · high leverage: h&gt;2p/N · "
                      "influential: Cook's D&gt;1.",
        "h_rec_case": "Recommended design for this case",
        "rec_match": "The executed design ({actual}) matches the one recommended for this "
                     "case: good choice.",
        "rec_diff": "For this case the most efficient design would be {method}; you ran "
                    "{actual}. This is informative, not an error: review the alternatives "
                    "table and choose by your priorities.",
        "h_conclusions": "Conclusions and recommendations",
        "foot": "Report generated by doekit {ver}. Rule-based narrative (deterministic). "
                "Regenerate: <code>doekit.report(design, response=...)</code>.",
        "plot_fail": "(the '{key}' plot could not be generated: {err})",
        "resid_x": "Fitted values", "resid_y": "Studentized residual",
        "resid_title": "Residual diagnostics",
        # methodology prose per design kind
        "kind_prose": {
            "PlackettBurman": "Plackett-Burman screening design: estimates main effects "
                              "orthogonally in the minimum number of runs.",
            "FractionalFactorial": "Fractional factorial: reduces runs by accepting "
                                   "confounding (aliasing) controlled by the resolution.",
            "FullFactorial": "Full factorial: every level combination.",
            "BoxBehnken": "Box-Behnken design: efficient response surface without points "
                          "at the cube vertices.",
            "CentralComposite": "Central Composite design: factorial + star points + center "
                                "points to fit a quadratic model.",
            "DefinitiveScreening": "Definitive Screening Design (Jones-Nachtsheim): main "
                                   "effects free of bias from curvature and interactions.",
            "OptimalDesign": "Optimal design: subset that maximizes information under the "
                             "chosen criterion, useful in constrained regions.",
            "LatinHypercube": "Latin Hypercube: sampling that covers the space uniformly.",
            "RandomDesign": "Random design from given distributions.",
        },
        "meth_default": "Design of type {kind}.",
        "meth_resolution": "Resolution {res} ({rel}).",
        "meth_alpha": "Star points at alpha={alpha:.3f} (type {kind}).",
        "meth_center": "Center points: {center}.",
        "meth_conf": "Conference order {order}",
        "meth_phantom": ", {n} phantom factors.",
        "meth_criterion": "Criterion {crit} via {algo}.",
        # executive summary
        "exec_saturated": "Saturated design: it does not estimate the specified model.",
        "exec_quality": "Design quality: D-efficiency {d:.0f}% ({level}), G-efficiency {g:.0f}%.",
        "lvl_excellent": "excellent", "lvl_acceptable": "acceptable",
        "lvl_rsm": "typical of a standard RSM", "lvl_low": "low",
        "exec_fit_saturated": "Saturated fit (dof=0): R2={r2:.3f} by construction; no "
                              "significance test: use the half-normal plot.",
        "exec_sig": "Significant terms: {terms}.",
        "exec_nosig": "No term significant at 5%.",
        "exec_r2": " R2={r2:.3f} (adjusted {r2adj:.3f}).",
        # recommendations
        "rec_saturated": "The design is saturated/supersaturated: it cannot estimate the "
                         "model. Reduce the number of terms or add runs.",
        "rec_d_rsm": "The relative D-efficiency ({d:.0f}%) is the one typical of a standard "
                     "design for a quadratic model; it does not indicate a defect.",
        "rec_d_nonstd": "The D-efficiency ({d:.0f}%) is below the acceptable threshold "
                        "({ok:.0f}%): increase n_starts, add runs or improve the candidate set.",
        "rec_fit_saturated": "Saturated design for the model (no degrees of freedom for a "
                             "significance test): identify the active effects with the "
                             "half-normal plot or the means.",
        "rec_screen_suffix": " The factors that pull away from the line are candidates for a "
                             "response-surface phase (box_behnken / central_composite).",
        "rec_addruns_suffix": " Add runs or replicates to enable inference.",
        "rec_sig": "Significant factors/terms (p<0.05): {terms}.",
        "rec_nosig": "No term was significant (p<0.05): review the factor ranges or the "
                     "experimental noise.",
        "rec_nextstep": "Next step: move to a response surface (box_behnken / "
                        "central_composite) on the active factors.",
        "rec_anom": "There are {n} atypical/influential run(s): review the anomalous-values "
                    "section before concluding.",
        # recommendation-table column display names
        "rec_cols": {"metodo": "method", "corridas": "runs", "D_eff": "D-eff",
                     "G_eff": "G-eff", "SPV_medio": "mean SPV",
                     "en_presupuesto": "in budget", "soporta_modelo": "supports model"},
    },
    "es": {
        "title_default": "Reporte DoE — {kind}",
        "sub": "Generado {now} · doekit {ver} · {runs} corridas, {params} parametros, dof={dof}",
        "h_exec": "Resumen ejecutivo",
        "recommendation": "Recomendacion",
        "h_method": "Metodologia",
        "h_factors": "Factores",
        "th_factor": "Factor", "th_type": "Tipo", "th_range": "Rango / niveles",
        "coded": "codificado", "model": "Modelo",
        "see_matrix": "Ver matriz del diseno ({runs} corridas)",
        "h_quality": "Calidad del diseno",
        "rank_deficient_q": "<b>Diseno saturado/supersaturado:</b> no puede estimar el "
                            "modelo; las eficiencias no estan definidas.",
        "card_d": "D-eficiencia", "card_a": "A-eficiencia", "card_g": "G-eficiencia",
        "gloss_eff": "La D-eficiencia mide informacion global de los estimados "
                     "(100% = ortogonal); la G, la peor varianza de prediccion en la region. "
                     "&ge;90% excelente, 70-90% aceptable, &lt;70% revisar.",
        "gloss_fds": "FDS: fraccion de la region (eje x) vs varianza de prediccion escalada "
                     "(eje y). Curva baja y plana = prediccion uniforme.",
        "h_power": "Potencia por termino",
        "gloss_power": "Probabilidad de detectar un efecto del tamano anticipado. "
                       "Objetivo &ge;{target:.0%}.",
        "vif_max": "VIF maximo", "vif_gloss": "(1 = ortogonal; &gt;5 indica multicolinealidad).",
        "h_alias": "Matriz de alias",
        "gloss_alias": "Sesgo de los coeficientes por terminos omitidos (interacciones de "
                       "dos factores). Celdas intensas = confusion fuerte.",
        "h_results": "Resultados del analisis",
        "results_line": "R&sup2; = {r2:.4f} · R&sup2; ajustado = {r2adj:.4f} · "
                        "sigma&sup2; = {s2:.4g} · dof = {dof}",
        "gloss_sig": "Significancia: *** p&lt;0.001, ** p&lt;0.01, * p&lt;0.05, . p&lt;0.1",
        "h_anom": "Valores anomalos",
        "no_anom": "No se detectaron corridas atipicas ni influyentes.",
        "gloss_anom": "outlier: |residuo studentizado|&gt;3 · alto leverage: h&gt;2p/N · "
                      "influyente: Cook's D&gt;1.",
        "h_rec_case": "Recomendacion de diseno para este caso",
        "rec_match": "El diseno ejecutado ({actual}) coincide con el recomendado para este "
                     "caso: buena eleccion.",
        "rec_diff": "Para este caso el diseno mas eficiente seria {method}; ejecutaste "
                    "{actual}. Es informativo, no un error: revisa la tabla de alternativas "
                    "y elige segun tus prioridades.",
        "h_conclusions": "Conclusiones y recomendaciones",
        "foot": "Reporte generado por doekit {ver}. Narrativa por reglas (determinista). "
                "Regenerar: <code>doekit.report(design, response=...)</code>.",
        "plot_fail": "(no se pudo generar la grafica '{key}': {err})",
        "resid_x": "Valores ajustados", "resid_y": "Residuo studentizado",
        "resid_title": "Diagnostico de residuos",
        "kind_prose": {
            "PlackettBurman": "Diseno de screening de Plackett-Burman: estima efectos "
                              "principales de forma ortogonal en el minimo de corridas.",
            "FractionalFactorial": "Factorial fraccional: reduce corridas aceptando "
                                   "confusion (aliasing) controlada por la resolucion.",
            "FullFactorial": "Factorial completo: todas las combinaciones de niveles.",
            "BoxBehnken": "Diseno de Box-Behnken: superficie de respuesta eficiente sin "
                          "puntos en los vertices del cubo.",
            "CentralComposite": "Diseno Central Composite: factorial + puntos estrella + "
                                "centrales para ajustar un modelo cuadratico.",
            "DefinitiveScreening": "Definitive Screening Design (Jones-Nachtsheim): efectos "
                                   "principales libres de sesgo de curvatura e interacciones.",
            "OptimalDesign": "Diseno optimo: subconjunto que maximiza la informacion segun "
                             "el criterio elegido, util en regiones restringidas.",
            "LatinHypercube": "Latin Hypercube: muestreo que cubre uniformemente el espacio.",
            "RandomDesign": "Diseno aleatorio desde distribuciones dadas.",
        },
        "meth_default": "Diseno de tipo {kind}.",
        "meth_resolution": "Resolucion {res} ({rel}).",
        "meth_alpha": "Puntos estrella a alpha={alpha:.3f} (tipo {kind}).",
        "meth_center": "Puntos centrales: {center}.",
        "meth_conf": "Orden de conferencia {order}",
        "meth_phantom": ", {n} factores fantasma.",
        "meth_criterion": "Criterio {crit} via {algo}.",
        "exec_saturated": "Diseno saturado: no estima el modelo especificado.",
        "exec_quality": "Calidad del diseno: D-eficiencia {d:.0f}% ({level}), "
                        "G-eficiencia {g:.0f}%.",
        "lvl_excellent": "excelente", "lvl_acceptable": "aceptable",
        "lvl_rsm": "tipica de un RSM estandar", "lvl_low": "baja",
        "exec_fit_saturated": "Ajuste saturado (dof=0): R2={r2:.3f} por construccion; sin "
                              "test de significancia: usa el half-normal plot.",
        "exec_sig": "Terminos significativos: {terms}.",
        "exec_nosig": "Ningun termino significativo al 5%.",
        "exec_r2": " R2={r2:.3f} (ajustado {r2adj:.3f}).",
        "rec_saturated": "El diseno esta saturado/supersaturado: no puede estimar el modelo. "
                         "Reduce el numero de terminos o aumenta las corridas.",
        "rec_d_rsm": "La D-eficiencia relativa ({d:.0f}%) es la tipica de un diseno estandar "
                     "para un modelo cuadratico; no indica un defecto.",
        "rec_d_nonstd": "La D-eficiencia ({d:.0f}%) esta por debajo del umbral aceptable "
                        "({ok:.0f}%): aumenta n_starts, anade corridas o mejora el candidate set.",
        "rec_fit_saturated": "Diseno saturado para el modelo (sin grados de libertad para "
                             "test de significancia): identifica los efectos activos con el "
                             "half-normal plot o las medias.",
        "rec_screen_suffix": " Los factores que se despegan de la recta son candidatos a una "
                             "fase de superficie de respuesta (box_behnken / central_composite).",
        "rec_addruns_suffix": " Anade corridas o replicas para poder hacer inferencia.",
        "rec_sig": "Factores/terminos significativos (p<0.05): {terms}.",
        "rec_nosig": "Ningun termino resulto significativo (p<0.05): revisa el rango de los "
                     "factores o el ruido experimental.",
        "rec_nextstep": "Siguiente paso: pasa a superficie de respuesta (box_behnken / "
                        "central_composite) en los factores activos.",
        "rec_anom": "Hay {n} corrida(s) atipica(s)/influyente(s): revisa la seccion de "
                    "valores anomalos antes de concluir.",
        "rec_cols": {"metodo": "metodo", "corridas": "corridas", "D_eff": "D-eff",
                     "G_eff": "G-eff", "SPV_medio": "SPV medio",
                     "en_presupuesto": "en presupuesto", "soporta_modelo": "soporta modelo"},
    },
}


def _t(lang: str, key: str):
    """Look up a report string for ``lang``, falling back to English."""
    table = _STRINGS.get(lang, _STRINGS["en"])
    return table[key] if key in table else _STRINGS["en"][key]


_KIND_TO_LABEL = {
    "PlackettBurman": "Plackett-Burman", "BoxBehnken": "Box-Behnken",
    "CentralComposite": "Central Composite", "DefinitiveScreening": "Definitive Screening",
    "FullFactorial": "Factorial completo", "OptimalDesign": "D-optimo",
}


def _infer_scenario(design: Design, model: Optional[Model]):
    """Infer (goal, factors, model_order, budget) from the executed design."""
    kind = design.metadata.get("kind", "")
    terms = model.terms if model is not None else []
    order = ("quadratic" if any(isinstance(t, Power) for t in terms)
             else "interactions" if any(isinstance(t, Interaction) for t in terms)
             else "linear")
    rsm = {"BoxBehnken", "CentralComposite"}
    goal = "optimization" if (kind in rsm or order == "quadratic") else "screening"
    spec = design.factors if design.factors else len(design.matrix.columns)
    return goal, spec, order, design.n_runs


def _recommendation_block(design: Design, model: Optional[Model]) -> Optional[dict]:
    """Run the advisor for the inferred scenario and compare it with what was run.

    Returns a data dict (``method``, ``actual``, ``matches``, ``note``,
    ``rationale``, ``table``, ``caveats``). The ``note``/``rationale``/``caveats``
    come from :func:`recommend_design` (Spanish); the HTML renderer builds its own
    localized note instead, but :func:`report_summary` exposes them as-is.
    """
    if model is None:
        return None
    from .recommend import recommend_design  # noqa: PLC0415
    goal, spec, order, budget = _infer_scenario(design, model)
    try:
        rec = recommend_design(goal, spec, budget=budget, model_order=order, n_region=3000)
    except Exception:
        return None
    actual = _KIND_TO_LABEL.get(design.metadata.get("kind", ""), design.metadata.get("kind", ""))
    matches = rec.method == actual
    if matches:
        note = (f"El diseno ejecutado ({actual}) coincide con el recomendado para este "
                "caso: buena eleccion.")
    else:
        note = (f"Para este caso ({goal}, {rec.scenario['n_factors']} factores, modelo "
                f"'{order}', presupuesto {budget}), el diseno mas eficiente seria "
                f"{rec.method}; ejecutaste {actual}. Es informativo, no un error: revisa la "
                "tabla de alternativas y elige segun tus prioridades.")
    return {"method": rec.method, "actual": actual, "matches": matches, "note": note,
            "rationale": rec.rationale, "table": rec.table, "caveats": rec.caveats}


def report_summary(design: Design, response=None, model: Optional[Model] = None,
                   effect_size=1.0, sigma: float = 1.0, alpha: float = 0.05,
                   seed: Optional[int] = None, thresholds: Optional[dict] = None,
                   lang: str = "en") -> dict:
    """Return the experiment's **semantic guide** without writing HTML.

    Same narrative content as the report (methodology, executive summary,
    recommendations, quality and anomalies) but as a data structure: useful to
    show inline in a notebook, or for an agent (MCP) to consume.

    Parameters
    ----------
    lang : {"en", "es"}, default "en"
        Language of the methodology/summary/recommendations prose.

    Returns
    -------
    dict
        Keys ``methodology``, ``quality``, ``executive_summary``,
        ``recommendations``, ``anomalies`` and ``recommendation``.
    """
    thr = {**_DEFAULT_THRESHOLDS, **(thresholds or {})}
    model = model or design.model
    ev = _evaluate(design, model=model, effect_size=effect_size, sigma=sigma,
                   alpha=alpha, seed=seed)
    fit = fit_linear_model(design, response, model=model) if response is not None else None
    return {
        "methodology": _methodology_prose(design, model, lang),
        "quality": ev.efficiencies,
        "executive_summary": _executive_summary(design, ev.efficiencies, fit, thr, lang),
        "recommendations": _recommendations(design, ev.efficiencies, fit, thr, lang),
        "anomalies": fit.anomalies() if fit is not None else None,
        "recommendation": _recommendation_block(design, model),
    }


def run_report_arg(design, response=None, model=None, report=None, **extra):
    """Normalize the functions' ``report=`` argument and generate the HTML.

    ``report`` accepts ``None``/``False`` (do nothing), ``True`` (default folder
    ``report/``), a folder path (``str``/``Path``) or an options ``dict`` for
    :func:`report`. Returns the written ``Path`` or ``None``.
    """
    if report is None or report is False:
        return None
    if report is True:
        opts = {}
    elif isinstance(report, dict):
        opts = dict(report)
    else:
        opts = {"output_dir": report}
    opts.setdefault("model", model)
    return report_html(design, response=response, **{**extra, **opts})


def _require_mpl():
    """Import matplotlib (Agg backend) or raise a helpful ImportError."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover
        raise ImportError("matplotlib is required for reports. "
                          "Install with 'pip install doekit[report]'.") from exc
    return plt


def _load_css() -> str:
    """Read the report stylesheet shipped in ``doekit/assets/report.css``."""
    return (_ASSETS / "report.css").read_text(encoding="utf-8")


def _fig_b64(fig) -> str:
    """Render a figure to a base64 data URI (self-contained mode) and close it."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
    import matplotlib.pyplot as plt  # noqa: PLC0415
    plt.close(fig)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def _fig_save(fig, path: Path) -> None:
    """Save a figure to a PNG file (folder mode) and close it."""
    fig.savefig(path, format="png", dpi=110, bbox_inches="tight")
    import matplotlib.pyplot as plt  # noqa: PLC0415
    plt.close(fig)


def _stars(p: float) -> str:
    """Return the significance-star string for a p-value."""
    if not np.isfinite(p):
        return ""
    return "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "." if p < 0.1 else ""


def _semaphore(value: float, good: float, ok: float) -> str:
    """Map a value to a semaphore color name (green/amber/red/gray)."""
    if not np.isfinite(value):
        return "gray"
    return "green" if value >= good else "amber" if value >= ok else "red"


# --- rule-based narrative ---------------------------------------------------

def _methodology_prose(design: Design, model: Model, lang: str = "en") -> str:
    """Build the localized methodology paragraph from the design metadata."""
    kind = design.metadata.get("kind", "Design")
    m = design.metadata
    prose = _t(lang, "kind_prose")
    parts = [prose.get(kind, _t(lang, "meth_default").format(kind=kind))]
    if m.get("resolution"):
        parts.append(_t(lang, "meth_resolution").format(res=m["resolution"],
                                                         rel=m.get("defining_relation", "")))
    if m.get("alpha_value"):
        parts.append(_t(lang, "meth_alpha").format(alpha=m["alpha_value"], kind=m.get("alpha", "")))
    if m.get("center") is not None:
        parts.append(_t(lang, "meth_center").format(center=m["center"]))
    if m.get("conference_order"):
        s = _t(lang, "meth_conf").format(order=m["conference_order"])
        s += (_t(lang, "meth_phantom").format(n=m["phantom_factors"])
              if m.get("phantom_factors") else ".")
        parts.append(s)
    if m.get("criterion"):
        parts.append(_t(lang, "meth_criterion").format(crit=m["criterion"],
                                                       algo=m.get("algorithm", "")))
    return " ".join(parts)


#: Standard template designs (their efficiency is what it is by construction).
_STANDARD_TEMPLATES = {"BoxBehnken", "CentralComposite", "DefinitiveScreening",
                       "PlackettBurman", "FullFactorial", "FractionalFactorial"}
_RSM_TEMPLATES = {"BoxBehnken", "CentralComposite", "DefinitiveScreening"}
_SCREENING = {"PlackettBurman", "FractionalFactorial", "DefinitiveScreening"}


def _sig_terms(fit) -> list[str]:
    """Return the names of the significant (p<0.05) non-intercept terms."""
    return [n for n, p in zip(fit.names, fit.pvalues)
            if n != "(Intercept)" and np.isfinite(p) and p < 0.05]


def _recommendations(design, eff, fit, thr, lang: str = "en") -> list[str]:
    """Build the localized list of actionable recommendation bullets."""
    recs = []
    kind = design.metadata.get("kind", "")
    if eff.get("rank_deficient"):
        recs.append(_t(lang, "rec_saturated"))
        return recs
    # D-efficiency: only actionable for NON-standard designs (optimal/custom).
    d = eff["D_efficiency"]
    if np.isfinite(d) and d < thr["d_ok"]:
        if kind in _RSM_TEMPLATES:
            recs.append(_t(lang, "rec_d_rsm").format(d=d))
        elif kind not in _STANDARD_TEMPLATES:
            recs.append(_t(lang, "rec_d_nonstd").format(d=d, ok=thr["d_ok"]))
    if fit is not None:
        if fit.dof <= 0:
            msg = _t(lang, "rec_fit_saturated")
            msg += (_t(lang, "rec_screen_suffix") if kind in _SCREENING
                    else _t(lang, "rec_addruns_suffix"))
            recs.append(msg)
        else:
            sig = _sig_terms(fit)
            if sig:
                recs.append(_t(lang, "rec_sig").format(terms=", ".join(sig)))
            else:
                recs.append(_t(lang, "rec_nosig"))
            if kind in _SCREENING and sig:
                recs.append(_t(lang, "rec_nextstep"))
        an = fit.anomalies()
        if len(an):
            recs.append(_t(lang, "rec_anom").format(n=len(an)))
    return recs


def _executive_summary(design, eff, fit, thr, lang: str = "en") -> list[str]:
    """Build the localized executive-summary bullets (quality + fit highlights)."""
    bullets = []
    if eff.get("rank_deficient"):
        bullets.append(_t(lang, "exec_saturated"))
        return bullets
    d = eff["D_efficiency"]
    kind = design.metadata.get("kind", "")
    if d >= thr["d_excellent"]:
        level = _t(lang, "lvl_excellent")
    elif d >= thr["d_ok"]:
        level = _t(lang, "lvl_acceptable")
    elif kind in _RSM_TEMPLATES:
        level = _t(lang, "lvl_rsm")
    else:
        level = _t(lang, "lvl_low")
    bullets.append(_t(lang, "exec_quality").format(d=d, level=level, g=eff["G_efficiency"]))
    if fit is not None:
        if fit.dof <= 0:
            bullets.append(_t(lang, "exec_fit_saturated").format(r2=fit.r_squared))
        else:
            sig = _sig_terms(fit)
            head = (_t(lang, "exec_sig").format(terms=", ".join(sig)) if sig
                    else _t(lang, "exec_nosig"))
            bullets.append(head + _t(lang, "exec_r2").format(r2=fit.r_squared,
                                                             r2adj=fit.r_squared_adj))
    return bullets


# --- figures ----------------------------------------------------------------

def _build_figures(plt, plotting, design, model, ev, eff, fit, lang):
    """Build the report figures. Returns ``(figures, failed)``.

    ``figures`` maps a key to a matplotlib figure for each plot that was built;
    ``failed`` maps a key to an error message for each plot that was attempted but
    raised (so the report can show a visible placeholder instead of dropping it).
    """
    figures, failed = {}, {}

    def attempt(key, builder):
        try:
            figures[key] = builder()
        except Exception as exc:  # pragma: no cover - defensive
            failed[key] = str(exc)

    if not eff.get("rank_deficient"):
        def _fds():
            _, ax = plt.subplots(figsize=(6.5, 3.8))
            plotting.fds_plot(ev.fds, ax=ax)
            return ax.figure
        attempt("fds", _fds)
    if len(ev.power):
        def _power():
            _, ax = plt.subplots(figsize=(6, 3.4))
            plotting.power_plot(ev.power, ax=ax)
            return ax.figure
        attempt("power", _power)

    def _alias():
        from .evaluate import alias_matrix  # noqa: PLC0415
        A = alias_matrix(design, model=model)
        if A.shape[1] == 0:
            return None
        _, ax = plt.subplots(figsize=(6, 4))
        plotting.alias_heatmap(A, ax=ax)
        return ax.figure
    A_fig = None
    try:
        A_fig = _alias()
    except Exception as exc:  # pragma: no cover - defensive
        failed["alias"] = str(exc)
    if A_fig is not None:
        figures["alias"] = A_fig

    if fit is not None:
        def _halfnormal():
            eff_s = fit.summary_frame()
            mask = eff_s["term"] != "(Intercept)"
            _, ax = plt.subplots(figsize=(6, 3.6))
            plotting.half_normal_plot(eff_s["estimate"][mask].to_numpy(),
                                      eff_s["term"][mask].tolist(), ax=ax)
            return ax.figure
        attempt("halfnormal", _halfnormal)
        if fit.fitted is not None and fit.dof > 0:
            def _resid():
                _, ax = plt.subplots(figsize=(6, 3.4))
                ax.scatter(fit.fitted, fit.studentized_resid, color="tab:blue")
                ax.axhline(0, color="k", lw=.8)
                ax.axhline(3, color="r", ls="--", lw=.8)
                ax.axhline(-3, color="r", ls="--", lw=.8)
                ax.set_xlabel(_t(lang, "resid_x"))
                ax.set_ylabel(_t(lang, "resid_y"))
                ax.set_title(_t(lang, "resid_title"))
                ax.grid(True, alpha=.3)
                return ax.figure
            attempt("resid", _resid)
    return figures, failed


def _write_data_csvs(data_dir: Path, design, ev, fit) -> None:
    """Export the report's underlying data as CSV files (folder mode)."""
    data_dir.mkdir(parents=True, exist_ok=True)
    design.matrix.to_csv(data_dir / "design_matrix.csv", index=False)
    pd.Series(ev.efficiencies, name="value").to_csv(data_dir / "efficiencies.csv")
    if len(ev.power):
        ev.power.to_csv(data_dir / "power.csv")
    if len(ev.vif):
        ev.vif.to_csv(data_dir / "vif.csv")
    ev.fds.to_csv(data_dir / "fds.csv", index=False)
    if fit is not None:
        fit.summary_frame().to_csv(data_dir / "coefficients.csv", index=False)
        fit.anomalies().to_csv(data_dir / "anomalies.csv", index=False)


# --- HTML construction -------------------------------------------------------

def _card(label, value, color):
    """Render a semaphore metric card."""
    v = f"{value:.0f}%" if np.isfinite(value) else "n/d"
    return (f'<div class="card"><div class="val {color}">{v}</div>'
            f'<div class="lbl">{label}</div></div>')


def report_html(design: Design, response=None, model: Optional[Model] = None,
                output_dir="report", filename: Optional[str] = None,
                title: Optional[str] = None, effect_size=1.0, sigma: float = 1.0,
                alpha: float = 0.05, thresholds: Optional[dict] = None,
                seed: Optional[int] = None, self_contained: bool = False,
                lang: str = "en", open_browser: bool = False) -> Path:
    """Generate an HTML report of the design (and its analysis if responses are given).

    Without ``response`` it produces a *design-quality* report; with ``response``,
    a *complete* one (analysis + anomalies).

    Parameters
    ----------
    design : Design
        The design (and, with ``response``, the executed experiment) to report.
    response : array-like, optional
        Measured response per run; enables the analysis and anomaly sections.
    model : Model, optional
        Model to evaluate/fit; resolved from the design if omitted.
    output_dir : str or Path, default "report"
        In folder mode, the report folder itself (holds ``index.html``,
        ``report.css``, ``images/`` and ``data/``). In self-contained mode, the
        directory the single ``.html`` is written to.
    filename : str, optional
        Name of the main HTML file (default ``index.html`` in folder mode, a
        timestamped name in self-contained mode).
    title : str, optional
        Report title; a default is built from the design kind.
    effect_size, sigma, alpha : float
        Passed to the evaluation (power analysis).
    thresholds : dict, optional
        Overrides for the quality thresholds (``d_excellent``, ``d_ok``,
        ``power_target``, ``vif_warn``).
    seed : int, optional
        Seed for the region sampling of the evaluation.
    self_contained : bool, default False
        If ``True``, write a single ``.html`` with inlined CSS and base64 plots.
        If ``False`` (default), write a folder with separate assets and data.
    lang : {"en", "es"}, default "en"
        Report language.
    open_browser : bool, default False
        Open the written report in the web browser.

    Returns
    -------
    pathlib.Path
        Path to the written HTML file (the ``index.html`` in folder mode).
    """
    plt = _require_mpl()
    from . import plotting  # noqa: PLC0415
    thr = {**_DEFAULT_THRESHOLDS, **(thresholds or {})}
    model = model or design.model
    kind = design.metadata.get("kind", "Design")
    title = title or _t(lang, "title_default").format(kind=kind)

    ev = _evaluate(design, model=model, effect_size=effect_size, sigma=sigma,
                   alpha=alpha, seed=seed)
    eff = ev.efficiencies
    fit = fit_linear_model(design, response, model=model) if response is not None else None

    figures, failed = _build_figures(plt, plotting, design, model, ev, eff, fit, lang)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if self_contained:
        imgs = {k: _fig_b64(f) for k, f in figures.items()}
        head = f"<style>{_load_css()}</style>"
        if filename is None:
            stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"reporte_{kind.lower()}_{stamp}.html"
    else:
        img_dir = out / "images"
        img_dir.mkdir(parents=True, exist_ok=True)
        imgs = {}
        for k, f in figures.items():
            _fig_save(f, img_dir / f"{k}.png")
            imgs[k] = f"images/{k}.png"
        _write_data_csvs(out / "data", design, ev, fit)
        (out / "report.css").write_text(_load_css(), encoding="utf-8")
        head = "<link rel='stylesheet' href='report.css'>"
        filename = filename or "index.html"

    html = _render_html(design, model, ev, eff, fit, imgs, failed, thr, title, head, lang)

    path = out / filename
    path.write_text(html, encoding="utf-8")
    if open_browser:  # pragma: no cover
        webbrowser.open(path.resolve().as_uri())
    return path


def _img_or_placeholder(S, imgs, failed, key, lang, alt=""):
    """Append an <img> tag, or a visible placeholder if the plot failed."""
    if key in imgs:
        S.append(f"<img src='{imgs[key]}' alt='{alt or key}'>")
    elif key in failed:
        S.append(f"<p class='warn'>{_t(lang, 'plot_fail').format(key=key, err=failed[key])}</p>")


def _render_html(design, model, ev, eff, fit, imgs, failed, thr, title, head, lang) -> str:
    """Assemble the full HTML document string from the computed pieces."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    d_col = _semaphore(eff["D_efficiency"], thr["d_excellent"], thr["d_ok"])
    a_col = _semaphore(eff["A_efficiency"], thr["d_excellent"], thr["d_ok"])
    g_col = _semaphore(eff["G_efficiency"], thr["d_excellent"], thr["d_ok"])
    verdict = "gray" if eff.get("rank_deficient") else d_col

    S = [f"<!doctype html><html lang='{lang}'><head><meta charset='utf-8'>",
         "<meta name='viewport' content='width=device-width,initial-scale=1'>",
         f"<title>{title}</title>{head}</head><body>"]
    S.append(f"<div class='hero {verdict}'><h1>{title}</h1>")
    S.append("<div class='sub'>" + _t(lang, "sub").format(
        now=now, ver=__version__, runs=ev.n_runs, params=ev.n_params, dof=ev.dof) + "</div></div>")

    # 1. executive summary
    S.append(f"<h2>{_t(lang, 'h_exec')}</h2><ul>")
    for b in _executive_summary(design, eff, fit, thr, lang):
        S.append(f"<li>{b}</li>")
    for r in _recommendations(design, eff, fit, thr, lang)[:1]:
        S.append(f"<li><b>{_t(lang, 'recommendation')}:</b> {r}</li>")
    S.append("</ul>")

    # 2. methodology
    S.append(f"<h2>{_t(lang, 'h_method')}</h2>")
    S.append(f"<p>{_methodology_prose(design, model, lang)}</p>")
    S.append(f"<h3>{_t(lang, 'h_factors')}</h3><table><thead><tr>"
             f"<th>{_t(lang, 'th_factor')}</th><th>{_t(lang, 'th_type')}</th>"
             f"<th>{_t(lang, 'th_range')}</th></tr></thead><tbody>")
    if design.factors:
        for f in design.factors:
            d = f.to_dict()
            rng = (f"[{d['low']}, {d['high']}]" if d["type"] == "continuous"
                   else str(d["levels"]))
            S.append(f"<tr><td>{d['name']}</td><td>{d['type']}</td><td>{rng}</td></tr>")
    else:
        for c in design.matrix.columns:
            vals = sorted(map(str, pd.unique(design.matrix[c])))[:6]
            S.append(f"<tr><td>{c}</td><td>{_t(lang, 'coded')}</td><td>{', '.join(vals)}</td></tr>")
    S.append("</tbody></table>")
    if model is not None:
        S.append(f"<p class='gloss'>{_t(lang, 'model')}: <code>{model!r}</code></p>")

    # 3. design matrix (collapsible)
    S.append(f"<details><summary>{_t(lang, 'see_matrix').format(runs=design.n_runs)}</summary>")
    S.append(design.matrix.round(4).to_html(border=0))
    S.append("</details>")

    # 4. design quality
    S.append(f"<h2>{_t(lang, 'h_quality')}</h2>")
    if eff.get("rank_deficient"):
        S.append(f"<p class='red'>{_t(lang, 'rank_deficient_q')}</p>")
    else:
        S.append("<div class='cards'>")
        S.append(_card(_t(lang, "card_d"), eff["D_efficiency"], d_col))
        S.append(_card(_t(lang, "card_a"), eff["A_efficiency"], a_col))
        S.append(_card(_t(lang, "card_g"), eff["G_efficiency"], g_col))
        S.append("</div>")
        S.append(f"<p class='gloss'>{_t(lang, 'gloss_eff')}</p>")
        if "fds" in imgs or "fds" in failed:
            _img_or_placeholder(S, imgs, failed, "fds", lang, "FDS plot")
            if "fds" in imgs:
                S.append(f"<p class='gloss'>{_t(lang, 'gloss_fds')}</p>")
    if "power" in imgs or "power" in failed:
        S.append(f"<h3>{_t(lang, 'h_power')}</h3>")
        _img_or_placeholder(S, imgs, failed, "power", lang, "power")
        if "power" in imgs:
            S.append(f"<p class='gloss'>{_t(lang, 'gloss_power').format(target=thr['power_target'])}</p>")
    if len(ev.vif):
        vmax = float(np.nanmax(ev.vif.to_numpy()))
        vcol = "red" if vmax > thr["vif_warn"] else "green"
        S.append(f"<p><b>{_t(lang, 'vif_max')}:</b> <span class='{vcol}'>{vmax:.2f}</span> "
                 f"{_t(lang, 'vif_gloss')}</p>")
    if "alias" in imgs or "alias" in failed:
        S.append(f"<h3>{_t(lang, 'h_alias')}</h3>")
        _img_or_placeholder(S, imgs, failed, "alias", lang, "alias")
        if "alias" in imgs:
            S.append(f"<p class='gloss'>{_t(lang, 'gloss_alias')}</p>")

    # 5. results
    if fit is not None:
        S.append(f"<h2>{_t(lang, 'h_results')}</h2>")
        S.append("<p>" + _t(lang, "results_line").format(
            r2=fit.r_squared, r2adj=fit.r_squared_adj, s2=fit.sigma2, dof=fit.dof) + "</p>")
        sf = fit.summary_frame().copy()
        sf["sig"] = [_stars(p) for p in sf["p_value"]]
        for c in ("estimate", "std_error", "t_value", "p_value"):
            sf[c] = sf[c].map(lambda x: f"{x:.4g}")
        S.append(sf.to_html(index=False, border=0, escape=False))
        S.append(f"<p class='gloss'>{_t(lang, 'gloss_sig')}</p>")
        _img_or_placeholder(S, imgs, failed, "halfnormal", lang, "half-normal")

    # 6. anomalous values
    if fit is not None:
        S.append(f"<h2>{_t(lang, 'h_anom')}</h2>")
        an = fit.anomalies()
        if len(an) == 0:
            S.append(f"<p class='green'>{_t(lang, 'no_anom')}</p>")
        else:
            _img_or_placeholder(S, imgs, failed, "resid", lang, "residuals")
            S.append(an.to_html(index=False, border=0, classes="anom"))
            S.append(f"<p class='gloss'>{_t(lang, 'gloss_anom')}</p>")

    # 6.5 recommended design for this case
    rec = _recommendation_block(design, model)
    if rec is not None:
        S.append(f"<h2>{_t(lang, 'h_rec_case')}</h2>")
        color = "green" if rec["matches"] else "amber"
        note = (_t(lang, "rec_match").format(actual=rec["actual"]) if rec["matches"]
                else _t(lang, "rec_diff").format(method=rec["method"], actual=rec["actual"]))
        S.append(f"<p class='{color}'>{note}</p>")
        tb = rec["table"].rename(columns=_t(lang, "rec_cols"))
        S.append(tb.to_html(index=False, border=0))

    # 7. conclusions and recommendations
    S.append(f"<h2>{_t(lang, 'h_conclusions')}</h2><ul>")
    for r in _recommendations(design, eff, fit, thr, lang):
        S.append(f"<li>{r}</li>")
    S.append("</ul>")

    # footer
    S.append(f"<div class='foot'>{_t(lang, 'foot').format(ver=__version__)}</div>")
    S.append("</body></html>")
    return "".join(S)
