"""Bilingual string catalog for HTML reports."""

from __future__ import annotations

_STRINGS = {
    "en": {
        "title_default": "DoE report — {kind}",
        "sub": "Generated {now} · doekit {ver} · {runs} runs, {params} params, dof={dof}",
        "h_exec": "Executive summary",
        "recommendation": "Recommendation",
        "h_method": "Methodology",
        "h_factors": "Factors",
        "th_factor": "Factor", "th_type": "Type", "th_range": "Range / levels",
        "coded": "coded", "model": "Model",
        "see_matrix": "View design matrix ({runs} runs)",
        "h_quality": "Design quality",
        "rank_deficient_q": "<b>Saturated/supersaturated design:</b> it cannot estimate "
                            "the model; efficiencies are undefined.",
        "card_d": "D-efficiency", "card_a": "A-efficiency", "card_g": "G-efficiency",
        "gloss_eff": "D-efficiency measures the overall information of the estimates "
                     "(100% = orthogonal); G, the worst prediction variance in the region. "
                     "&ge;90% excellent, 70-90% acceptable, &lt;70% review.",
        "gloss_fds": "FDS: fraction of the region (x-axis) vs. scaled prediction variance "
                     "(y-axis). A low, flat curve = uniform prediction.",
        "h_power": "Power by term",
        "gloss_power": "Probability of detecting an effect of the anticipated size. "
                       "Target &ge;{target:.0%}.",
        "vif_max": "Max VIF", "vif_gloss": "(1 = orthogonal; &gt;5 indicates multicollinearity).",
        "h_alias": "Alias matrix",
        "gloss_alias": "Coefficient bias from omitted terms (two-factor interactions). "
                       "Intense cells = strong confounding.",
        "h_results": "Analysis results",
        "results_line": "R&sup2; = {r2:.4f} · adjusted R&sup2; = {r2adj:.4f} · "
                        "sigma&sup2; = {s2:.4g} · dof = {dof}",
        "gloss_sig": "Significance: *** p&lt;0.001, ** p&lt;0.01, * p&lt;0.05, . p&lt;0.1",
        "h_anom": "Anomalous values",
        "no_anom": "No atypical or influential runs detected.",
        "gloss_anom": "outlier: |studentized residual|&gt;3 · high leverage: h&gt;2p/N · "
                      "influential: Cook's D&gt;1.",
        "h_rec_case": "Recommended design for this case",
        "rec_match": "The executed design ({actual}) matches the one recommended for this "
                     "case: good choice.",
        "rec_diff": "For this case the most efficient design would be {method}; you ran "
                    "{actual}. This is informative, not an error: review the alternatives "
                    "table and choose by your priorities.",
        "h_conclusions": "Conclusions and recommendations",
        "foot": "Report generated by doekit {ver}. Rule-based narrative (deterministic). "
                "Regenerate: <code>doekit.report(design, response=...)</code>.",
        "plot_fail": "(the '{key}' plot could not be generated: {err})",
        "resid_x": "Fitted values", "resid_y": "Studentized residual",
        "resid_title": "Residual diagnostics",
        # methodology prose per design kind
        "kind_prose": {
            "PlackettBurman": "Plackett-Burman screening design: estimates main effects "
                              "orthogonally in the minimum number of runs.",
            "FractionalFactorial": "Fractional factorial: reduces runs by accepting "
                                   "confounding (aliasing) controlled by the resolution.",
            "FullFactorial": "Full factorial: every level combination.",
            "BoxBehnken": "Box-Behnken design: efficient response surface without points "
                          "at the cube vertices.",
            "CentralComposite": "Central Composite design: factorial + star points + center "
                                "points to fit a quadratic model.",
            "DefinitiveScreening": "Definitive Screening Design (Jones-Nachtsheim): main "
                                   "effects free of bias from curvature and interactions.",
            "OptimalDesign": "Optimal design: subset that maximizes information under the "
                             "chosen criterion, useful in constrained regions.",
            "LatinHypercube": "Latin Hypercube: sampling that covers the space uniformly.",
            "RandomDesign": "Random design from given distributions.",
        },
        "meth_default": "Design of type {kind}.",
        "meth_resolution": "Resolution {res} ({rel}).",
        "meth_alpha": "Star points at alpha={alpha:.3f} (type {kind}).",
        "meth_center": "Center points: {center}.",
        "meth_conf": "Conference order {order}",
        "meth_phantom": ", {n} phantom factors.",
        "meth_criterion": "Criterion {crit} via {algo}.",
        # executive summary
        "exec_saturated": "Saturated design: it does not estimate the specified model.",
        "exec_quality": "Design quality: D-efficiency {d:.0f}% ({level}), G-efficiency {g:.0f}%.",
        "lvl_excellent": "excellent", "lvl_acceptable": "acceptable",
        "lvl_rsm": "typical of a standard RSM", "lvl_low": "low",
        "exec_fit_saturated": "Saturated fit (dof=0): R2={r2:.3f} by construction; no "
                              "significance test: use the half-normal plot.",
        "exec_sig": "Significant terms: {terms}.",
        "exec_nosig": "No term significant at 5%.",
        "exec_r2": " R2={r2:.3f} (adjusted {r2adj:.3f}).",
        # recommendations
        "rec_saturated": "The design is saturated/supersaturated: it cannot estimate the "
                         "model. Reduce the number of terms or add runs.",
        "rec_d_rsm": "The relative D-efficiency ({d:.0f}%) is the one typical of a standard "
                     "design for a quadratic model; it does not indicate a defect.",
        "rec_d_nonstd": "The D-efficiency ({d:.0f}%) is below the acceptable threshold "
                        "({ok:.0f}%): increase n_starts, add runs or improve the candidate set.",
        "rec_fit_saturated": "Saturated design for the model (no degrees of freedom for a "
                             "significance test): identify the active effects with the "
                             "half-normal plot or the means.",
        "rec_screen_suffix": " The factors that pull away from the line are candidates for a "
                             "response-surface phase (box_behnken / central_composite).",
        "rec_addruns_suffix": " Add runs or replicates to enable inference.",
        "rec_sig": "Significant factors/terms (p<0.05): {terms}.",
        "rec_nosig": "No term was significant (p<0.05): review the factor ranges or the "
                     "experimental noise.",
        "rec_nextstep": "Next step: move to a response surface (box_behnken / "
                        "central_composite) on the active factors.",
        "rec_anom": "There are {n} atypical/influential run(s): review the anomalous-values "
                    "section before concluding.",
        # recommendation-table column display names (keys = Recommendation.table cols)
        "rec_cols": {"method": "method", "runs": "runs", "D_eff": "D-eff",
                     "G_eff": "G-eff", "SPV_mean": "mean SPV",
                     "in_budget": "in budget", "supports_model": "supports model"},
    },
    "es": {
        "title_default": "Reporte DoE — {kind}",
        "sub": "Generado {now} · doekit {ver} · {runs} corridas, {params} parametros, dof={dof}",
        "h_exec": "Resumen ejecutivo",
        "recommendation": "Recomendacion",
        "h_method": "Metodologia",
        "h_factors": "Factores",
        "th_factor": "Factor", "th_type": "Tipo", "th_range": "Rango / niveles",
        "coded": "codificado", "model": "Modelo",
        "see_matrix": "Ver matriz del diseno ({runs} corridas)",
        "h_quality": "Calidad del diseno",
        "rank_deficient_q": "<b>Diseno saturado/supersaturado:</b> no puede estimar el "
                            "modelo; las eficiencias no estan definidas.",
        "card_d": "D-eficiencia", "card_a": "A-eficiencia", "card_g": "G-eficiencia",
        "gloss_eff": "La D-eficiencia mide informacion global de los estimados "
                     "(100% = ortogonal); la G, la peor varianza de prediccion en la region. "
                     "&ge;90% excelente, 70-90% aceptable, &lt;70% revisar.",
        "gloss_fds": "FDS: fraccion de la region (eje x) vs varianza de prediccion escalada "
                     "(eje y). Curva baja y plana = prediccion uniforme.",
        "h_power": "Potencia por termino",
        "gloss_power": "Probabilidad de detectar un efecto del tamano anticipado. "
                       "Objetivo &ge;{target:.0%}.",
        "vif_max": "VIF maximo", "vif_gloss": "(1 = ortogonal; &gt;5 indica multicolinealidad).",
        "h_alias": "Matriz de alias",
        "gloss_alias": "Sesgo de los coeficientes por terminos omitidos (interacciones de "
                       "dos factores). Celdas intensas = confusion fuerte.",
        "h_results": "Resultados del analisis",
        "results_line": "R&sup2; = {r2:.4f} · R&sup2; ajustado = {r2adj:.4f} · "
                        "sigma&sup2; = {s2:.4g} · dof = {dof}",
        "gloss_sig": "Significancia: *** p&lt;0.001, ** p&lt;0.01, * p&lt;0.05, . p&lt;0.1",
        "h_anom": "Valores anomalos",
        "no_anom": "No se detectaron corridas atipicas ni influyentes.",
        "gloss_anom": "outlier: |residuo studentizado|&gt;3 · alto leverage: h&gt;2p/N · "
                      "influyente: Cook's D&gt;1.",
        "h_rec_case": "Recomendacion de diseno para este caso",
        "rec_match": "El diseno ejecutado ({actual}) coincide con el recomendado para este "
                     "caso: buena eleccion.",
        "rec_diff": "Para este caso el diseno mas eficiente seria {method}; ejecutaste "
                    "{actual}. Es informativo, no un error: revisa la tabla de alternativas "
                    "y elige segun tus prioridades.",
        "h_conclusions": "Conclusiones y recomendaciones",
        "foot": "Reporte generado por doekit {ver}. Narrativa por reglas (determinista). "
                "Regenerar: <code>doekit.report(design, response=...)</code>.",
        "plot_fail": "(no se pudo generar la grafica '{key}': {err})",
        "resid_x": "Valores ajustados", "resid_y": "Residuo studentizado",
        "resid_title": "Diagnostico de residuos",
        "kind_prose": {
            "PlackettBurman": "Diseno de screening de Plackett-Burman: estima efectos "
                              "principales de forma ortogonal en el minimo de corridas.",
            "FractionalFactorial": "Factorial fraccional: reduce corridas aceptando "
                                   "confusion (aliasing) controlada por la resolucion.",
            "FullFactorial": "Factorial completo: todas las combinaciones de niveles.",
            "BoxBehnken": "Diseno de Box-Behnken: superficie de respuesta eficiente sin "
                          "puntos en los vertices del cubo.",
            "CentralComposite": "Diseno Central Composite: factorial + puntos estrella + "
                                "centrales para ajustar un modelo cuadratico.",
            "DefinitiveScreening": "Definitive Screening Design (Jones-Nachtsheim): efectos "
                                   "principales libres de sesgo de curvatura e interacciones.",
            "OptimalDesign": "Diseno optimo: subconjunto que maximiza la informacion segun "
                             "el criterio elegido, util en regiones restringidas.",
            "LatinHypercube": "Latin Hypercube: muestreo que cubre uniformemente el espacio.",
            "RandomDesign": "Diseno aleatorio desde distribuciones dadas.",
        },
        "meth_default": "Diseno de tipo {kind}.",
        "meth_resolution": "Resolucion {res} ({rel}).",
        "meth_alpha": "Puntos estrella a alpha={alpha:.3f} (tipo {kind}).",
        "meth_center": "Puntos centrales: {center}.",
        "meth_conf": "Orden de conferencia {order}",
        "meth_phantom": ", {n} factores fantasma.",
        "meth_criterion": "Criterio {crit} via {algo}.",
        "exec_saturated": "Diseno saturado: no estima el modelo especificado.",
        "exec_quality": "Calidad del diseno: D-eficiencia {d:.0f}% ({level}), "
                        "G-eficiencia {g:.0f}%.",
        "lvl_excellent": "excelente", "lvl_acceptable": "aceptable",
        "lvl_rsm": "tipica de un RSM estandar", "lvl_low": "baja",
        "exec_fit_saturated": "Ajuste saturado (dof=0): R2={r2:.3f} por construccion; sin "
                              "test de significancia: usa el half-normal plot.",
        "exec_sig": "Terminos significativos: {terms}.",
        "exec_nosig": "Ningun termino significativo al 5%.",
        "exec_r2": " R2={r2:.3f} (ajustado {r2adj:.3f}).",
        "rec_saturated": "El diseno esta saturado/supersaturado: no puede estimar el modelo. "
                         "Reduce el numero de terminos o aumenta las corridas.",
        "rec_d_rsm": "La D-eficiencia relativa ({d:.0f}%) es la tipica de un diseno estandar "
                     "para un modelo cuadratico; no indica un defecto.",
        "rec_d_nonstd": "La D-eficiencia ({d:.0f}%) esta por debajo del umbral aceptable "
                        "({ok:.0f}%): aumenta n_starts, anade corridas o mejora el candidate set.",
        "rec_fit_saturated": "Diseno saturado para el modelo (sin grados de libertad para "
                             "test de significancia): identifica los efectos activos con el "
                             "half-normal plot o las medias.",
        "rec_screen_suffix": " Los factores que se despegan de la recta son candidatos a una "
                             "fase de superficie de respuesta (box_behnken / central_composite).",
        "rec_addruns_suffix": " Anade corridas o replicas para poder hacer inferencia.",
        "rec_sig": "Factores/terminos significativos (p<0.05): {terms}.",
        "rec_nosig": "Ningun termino resulto significativo (p<0.05): revisa el rango de los "
                     "factores o el ruido experimental.",
        "rec_nextstep": "Siguiente paso: pasa a superficie de respuesta (box_behnken / "
                        "central_composite) en los factores activos.",
        "rec_anom": "Hay {n} corrida(s) atipica(s)/influyente(s): revisa la seccion de "
                    "valores anomalos antes de concluir.",
        "rec_cols": {"method": "metodo", "runs": "corridas", "D_eff": "D-eff",
                     "G_eff": "G-eff", "SPV_mean": "SPV medio",
                     "in_budget": "en presupuesto", "supports_model": "soporta modelo"},
    },
}


def _t(lang: str, key: str):
    """Look up a report string for ``lang``, falling back to English."""
    table = _STRINGS.get(lang, _STRINGS["en"])
    return table[key] if key in table else _STRINGS["en"][key]


_KIND_TO_LABEL = {
    "PlackettBurman": "Plackett-Burman", "BoxBehnken": "Box-Behnken",
    "CentralComposite": "Central Composite", "DefinitiveScreening": "Definitive Screening",
    "FullFactorial": "Full factorial", "OptimalDesign": "D-optimal",
}


