"""Definitive Screening Designs (DSD), Jones & Nachtsheim (2011).

In ``2*m+1`` runs (for ``m`` factors) they allow you to:

- estimate all main effects **free of bias** from two-factor interactions and
  curvature (main effects orthogonal to the second-order terms);
- estimate quadratic effects of all factors (3 levels: ``-1, 0, +1``);
- project onto response surfaces in the few active factors without additional
  experiments.

Construction: given a **conference matrix** ``C`` of order ``m`` (zero diagonal,
``+/-1`` off-diagonal, ``C^T C = (m-1) I``), the DSD is::

    [[ C ],
     [-C ],
     [ 0 ]]

The ``C``/``-C`` fold makes the linear effects (odd functions) orthogonal to the
quadratics and interactions (even functions). Here the conference matrices are
generated by the **Paley** construction (order ``q+1`` with ``q`` prime),
covering orders ``4, 6, 8, 12, 14, 18, 20, 24, ...``.

> Jones, B. & Nachtsheim, C.J. (2011). A class of three-level designs for
> definitive screening in the presence of second-order effects. *Journal of
> Quality Technology*, 43(1), 1-15.
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd

from ...domain.model import Model
from ...domain.design import Design
from ._shared import resolve_factors as _resolve_factors
from ._shared import decode_coded as _decode
from ._shared import is_prime as _is_prime
from ._shared import legendre as _legendre


def _paley_conference(order: int) -> Optional[np.ndarray]:
    """Conference matrix of order ``order`` via the Paley construction.

    Returns ``C`` (``order x order``, zero diagonal, ``+/-1`` off-diagonal,
    ``C^T C = (order-1) I``) or ``None`` if ``order-1`` is not prime.
    """
    q = order - 1
    if q < 1 or not _is_prime(q):
        return None
    Q = np.array([[_legendre(a - b, q) for b in range(q)] for a in range(q)], dtype=float)
    C = np.zeros((order, order))
    e = np.ones(q)
    C[0, 1:] = e
    C[1:, 0] = e if q % 4 == 1 else -e  # symmetric (q=1 mod4) / skew (q=3 mod4)
    C[1:, 1:] = Q
    # numerical validation of the conference property
    if not np.allclose(np.diag(C), 0):
        return None
    off = C[~np.eye(order, dtype=bool)]
    if not np.all(np.isin(off, (-1.0, 1.0))):
        return None
    if not np.allclose(C.T @ C, (order - 1) * np.eye(order)):
        return None
    return C


def _next_conference_order(min_order: int) -> tuple[int, np.ndarray]:
    """Smallest order ``>= min_order`` with a constructible Paley conference matrix."""
    n = max(2, min_order)
    if n == 2:
        return 2, np.array([[0.0, 1.0], [1.0, 0.0]])
    while n <= 4 * min_order + 12:
        C = _paley_conference(n)
        if C is not None:
            return n, C
        n += 1
    raise ValueError(f"no constructible conference matrix found near {min_order}")


def definitive_screening(factors, extra_center: int = 0,
                         model: Optional[Model] = None) -> Design:
    """Definitive Screening Design for the given factors.

    Parameters
    ----------
    factors : int or dict or sequence of Factor
        An integer (``m`` factors coded in ``-1/0/+1``), a dict
        ``{name: (low, high)}`` or a list of :class:`Factor` (the matrix is
        decoded to natural units using ``low -> -1``, ``mid -> 0``,
        ``high -> +1``).
    extra_center : int, default 0
        Number of additional center points.
    model : Model, optional
        Model to attach; defaults to a main-effects model with intercept.

    Returns
    -------
    Design
        The DSD in ``2*m0+1`` runs, where ``m0`` is the smallest constructible
        conference order ``>= m``. When ``m0 > m`` the surplus columns are dropped
        (equivalent to using "phantom" factors, which further reduces estimate
        bias, as recommended by Jones & Nachtsheim). ``metadata`` carries
        ``conference_order``, ``n_center`` and ``phantom_factors``.

    Raises
    ------
    ValueError
        If fewer than 2 factors are given.
    """
    names, facs = _resolve_factors(factors)
    m = len(names)
    if m < 2:
        raise ValueError("Definitive Screening requires >= 2 factors")

    m0, C = _next_conference_order(m)
    cols = C[:, :m]                       # first m columns
    coded = np.vstack([cols, -cols, np.zeros((1 + extra_center, m))])

    natural = _decode(coded, facs)
    df = pd.DataFrame(natural, columns=names)
    if model is None:
        # Screening model: main effects (dof > 0). The DSD additionally ALLOWS
        # estimating the quadratics of the active factors after screening (pass a
        # Model with Power(., 2) for that second-order projection).
        model = Model.main_effects(names, intercept=True)
    meta = {
        "kind": "DefinitiveScreening",
        "conference_order": m0,
        "n_center": 1 + extra_center,
        "phantom_factors": m0 - m,
    }
    return Design(matrix=df, factors=facs or [], model=model, metadata=meta)
