"""Full and fractional factorial designs.

- ``full_factorial``: every level combination (explicit or lazy iterator).
- ``fractional_factorial``: a real ``2^(k-p)`` fraction from generators, with the
  defining relation, resolution and alias structure.
"""

from __future__ import annotations

import string
from itertools import combinations, product
from typing import Iterable, Iterator, Optional, Sequence

import numpy as np
import pandas as pd

from ...domain.factors import Factor, as_factors
from ...domain.model import Model
from ...domain.design import Design


# --- Full factorial --------------------------------------------------------

def _cartesian_first_fastest(levels: Sequence[Sequence]) -> list[tuple]:
    """Cartesian product with the FIRST factor varying fastest."""
    combos = product(*[list(l) for l in reversed(levels)])
    return [tuple(reversed(c)) for c in combos]


def _normalize_levels(spec) -> tuple[list[str], list[list]]:
    """Return (names, levels) from a dict / list-of-lists / int spec."""
    if isinstance(spec, int):
        names = [f"factor{i + 1}" for i in range(spec)]
        levels = [[-1, 1] for _ in range(spec)]
        return names, levels
    if isinstance(spec, dict):
        return list(spec.keys()), [list(v) for v in spec.values()]
    # list of level lists
    levels = [list(v) for v in spec]
    names = [f"factor{i + 1}" for i in range(len(levels))]
    return names, levels


def full_factorial(levels, names: Optional[Sequence[str]] = None,
                   model: Optional[Model] = None, lazy: bool = False):
    """Build a full factorial design (all level combinations).

    The Cartesian product uses the **first factor varying fastest** (standard
    DoE ordering). Pass ``lazy=True`` to stream rows without materializing the
    full matrix.

    Parameters
    ----------
    levels : int or dict or list of list
        An integer (``n`` two-level factors), a dict ``{name: [levels]}`` or a
        list of level lists.
    names : sequence of str, optional
        Factor names; defaults to ``factor1..factorn``.
    model : Model, optional
        Model to attach to the design.
    lazy : bool, default False
        If ``True``, return a row iterator instead of materializing the matrix.

    Returns
    -------
    Design or iterator of dict
        The full factorial design, or a row iterator when ``lazy=True``.

    Examples
    --------
    >>> import doekit as ed
    >>> d = ed.full_factorial(2)
    >>> d.n_runs, d.n_factors
    (4, 2)
    """
    default_names, lv = _normalize_levels(levels)
    names = list(names) if names is not None else default_names

    if lazy:
        return _full_factorial_iter(lv, names)

    rows = _cartesian_first_fastest(lv)
    df = pd.DataFrame(rows, columns=names)
    return Design(matrix=df, model=model, metadata={"kind": "FullFactorial"})


def _full_factorial_iter(levels: Sequence[Sequence], names: Sequence[str]) -> Iterator[dict]:
    for combo in product(*[list(l) for l in reversed(levels)]):
        yield dict(zip(names, reversed(combo)))


# --- Fractional factorial (real) -------------------------------------------

def _letters(k: int) -> list[str]:
    """Return the first ``k`` uppercase letters used as factor symbols (A..Z)."""
    if k > 26:
        raise ValueError("fractional_factorial supports up to 26 factors (A..Z)")
    return list(string.ascii_uppercase[:k])


def _parse_generators(generators: Sequence[str]) -> dict[str, frozenset[str]]:
    """``["D=ABC", "E=AB"]`` -> ``{"D": {"A","B","C"}, "E": {"A","B"}}``."""
    parsed: dict[str, frozenset[str]] = {}
    for g in generators:
        lhs, rhs = g.replace(" ", "").upper().split("=")
        parsed[lhs] = frozenset(rhs)
    return parsed


def _defining_group(words: Sequence[frozenset[str]]) -> set[frozenset[str]]:
    """Closure of the group generated by ``words`` under symmetric difference (XOR)."""
    group: set[frozenset[str]] = {frozenset()}  # identidad I
    for w in words:
        group |= {g ^ w for g in group}
    return group


def fractional_factorial(n_factors: int, generators: Sequence[str],
                         names: Optional[Sequence[str]] = None,
                         model: Optional[Model] = None) -> Design:
    """Build a real ``2^(k-p)`` fractional factorial design.

    Base factors form a full ``2^(k-p)`` factorial at ``±1``; generated factors
    are products of base columns. Metadata includes defining relation,
    resolution, and alias classes.

    Formulas
    --------
    Generator ``D = ABC`` implies column ``D = A * B * C`` (element-wise product
    of ``±1`` columns). Defining relation from the group generated by generators
    under symmetric difference; resolution = length of shortest word ≠ ``I``.

    Parameters
    ----------
    n_factors : int
        Total number of factors ``k``.
    generators : sequence of str
        Definition of the ``p`` extra factors as products of the base factors,
        e.g. ``["C=AB"]`` for ``2^(3-1)`` or ``["D=AB", "E=AC"]`` for
        ``2^(5-2)``. Letters ``A, B, ...`` refer to the factors in order.
    names : sequence of str, optional
        Factor names; defaults to ``factor1..factorn``.
    model : Model, optional
        Model to attach to the design.

    Returns
    -------
    Design
        The fractional design, carrying in ``metadata`` the ``generators``,
        ``defining_relation``, ``resolution`` and ``aliases`` (alias classes).

    Raises
    ------
    ValueError
        When generators are inconsistent with ``n_factors`` or reference unknown
        base factors.

    Examples
    --------
    >>> import doekit as ed
    >>> d = ed.fractional_factorial(3, ["C=AB"])
    >>> d.metadata["resolution"]
    'III'
    """
    letters = _letters(n_factors)
    names = list(names) if names is not None else [f"factor{i + 1}" for i in range(n_factors)]
    letter_to_name = dict(zip(letters, names))

    gens = _parse_generators(generators)
    defined = set(gens.keys())
    base = [l for l in letters if l not in defined]
    p = len(gens)
    if len(base) != n_factors - p:
        raise ValueError("the generators are inconsistent with n_factors")

    # full factorial of the base factors at 2 levels (+/-1)
    base_rows = _cartesian_first_fastest([[-1, 1] for _ in base])
    base_arr = np.array(base_rows)  # (2^(k-p), k-p)
    col_of = {l: base_arr[:, i] for i, l in enumerate(base)}

    # defined factors = product of base columns
    for new, rhs in gens.items():
        col = np.ones(base_arr.shape[0], dtype=int)
        for src in rhs:
            if src not in col_of:
                raise ValueError(f"generator {new}={''.join(rhs)}: '{src}' is not a base factor")
            col = col * col_of[src]
        col_of[new] = col

    matrix = np.column_stack([col_of[l] for l in letters])
    df = pd.DataFrame(matrix, columns=names)

    # defining relation and resolution
    words = [frozenset(rhs | {new}) for new, rhs in gens.items()]
    group = _defining_group(words)
    non_id = [w for w in group if w]
    resolution = min(len(w) for w in non_id) if non_id else None

    defining_relation = "I = " + " = ".join(
        "".join(sorted(w)) for w in sorted(non_id, key=lambda s: (len(s), sorted(s)))
    ) if non_id else "I"

    aliases = _alias_classes(letters, group, letter_to_name)

    meta = {
        "kind": "FractionalFactorial",
        "generators": list(generators),
        "defining_relation": defining_relation,
        "resolution": _roman(resolution) if resolution else None,
        "aliases": aliases,
    }
    return Design(matrix=df, model=model, metadata=meta)


def _alias_classes(letters: Sequence[str], group: set[frozenset[str]],
                   letter_to_name: dict[str, str]) -> list[list[str]]:
    """Partition the effects (up to order k) into alias classes."""
    all_effects: list[frozenset[str]] = []
    for r in range(1, len(letters) + 1):
        for combo in combinations(letters, r):
            all_effects.append(frozenset(combo))

    seen: set[frozenset[str]] = set()
    classes: list[list[str]] = []
    for eff in all_effects:
        if eff in seen:
            continue
        orbit = {eff ^ w for w in group}
        orbit_effects = {o for o in orbit if o}  # drop the I block (the mean)
        seen |= orbit_effects
        labels = sorted(
            (":".join(letter_to_name[l] for l in sorted(o)) for o in orbit_effects),
            key=lambda s: (s.count(":"), s),
        )
        if labels:
            classes.append(labels)
    return classes


def _roman(n: int) -> str:
    numerals = {1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII", 8: "VIII"}
    return numerals.get(n, str(n))
