#!/usr/bin/env python3
"""Generate Fumadocs MDX API pages from Python docstrings via Griffe.

Reads docs_v4/api-config.json and writes static MDX under content/docs/api/.
MkDocs continues to use live mkdocstrings directives; this pipeline is for docs_v4 only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable, Sequence

import griffe
from griffe import DocstringSectionKind, ObjectKind, ParameterKind

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = REPO_ROOT / "docs_v4" / "api-config.json"
BANNER = (
    '<Callout title="Generated" type="info">'
    "Generated by utils/gen_api_mdx.py; do not edit"
    "</Callout>"
)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="Path to api-config.json (default: docs_v4/api-config.json)",
    )
    args = parser.parse_args(argv)

    config_path = args.config.resolve()
    if not config_path.is_file():
        print(f"error: config not found: {config_path}", file=sys.stderr)
        return 1

    docs_v4 = config_path.parent
    with config_path.open(encoding="utf-8") as fh:
        config = json.load(fh)

    options = config.get("options") or {}
    output_dir = docs_v4 / config.get("output_dir", "content/docs/api")
    output_dir.mkdir(parents=True, exist_ok=True)

    search_paths = [str(REPO_ROOT)]
    errors: list[str] = []

    for page in config.get("pages") or []:
        try:
            body = render_page(page, options, search_paths)
        except Exception as exc:  # noqa: BLE001 — surface all load/render failures
            errors.append(f"{page.get('file', '?')}: {exc}")
            continue
        out_path = output_dir / page["file"]
        out_path.write_text(body, encoding="utf-8", newline="\n")
        print(f"wrote {out_path.relative_to(REPO_ROOT)}")

    if errors:
        for err in errors:
            print(f"error: {err}", file=sys.stderr)
        return 1
    return 0


def render_page(page: dict[str, Any], options: dict[str, Any], search_paths: list[str]) -> str:
    title = page["title"]
    description = page.get("description") or title
    heading_level = int(options.get("heading_level", 2))
    members_from_all = bool(options.get("members_from_all", True))
    skip_private = bool(options.get("skip_private", True))
    style = options.get("docstring_style", "numpy")

    parts: list[str] = [
        "---",
        f'title: "{_yaml_escape(title)}"',
        f'description: "{_yaml_escape(description)}"',
        "---",
        "",
    ]
    if options.get("banner", False):
        banner = options.get("banner_text") or BANNER
        parts.append(str(banner))
        parts.append("")

    for section in page.get("sections") or []:
        heading = section["heading"]
        target = section["target"]
        parts.append(f"{'#' * heading_level} {heading}")
        parts.append("")
        try:
            module = griffe.load(
                target,
                search_paths=search_paths,
                docstring_parser=style,
                resolve_aliases=True,
                resolve_external=False,
                allow_inspection=True,
            )
        except Exception as exc:
            raise RuntimeError(f"failed to load {target!r}: {exc}") from exc

        module = _unwrap(module)
        if module.docstring and module.docstring.value:
            summary = _mdx_escape_prose(_first_paragraph(module.docstring.value))
            if summary:
                parts.append(summary)
                parts.append("")

        for name, member in _iter_public_members(module, members_from_all, skip_private):
            parts.extend(
                render_object(
                    member,
                    display_name=name,
                    heading_level=heading_level + 1,
                    skip_private=skip_private,
                )
            )

    text = "\n".join(parts).rstrip() + "\n"
    return text


def _iter_public_members(
    module: griffe.Object,
    members_from_all: bool,
    skip_private: bool,
) -> Iterable[tuple[str, griffe.Object]]:
    exports = getattr(module, "exports", None)
    use_exports = bool(members_from_all and exports)
    names: list[str] = [str(n) for n in exports] if use_exports else list(module.members.keys())

    seen: set[str] = set()
    for name in names:
        if name in seen:
            continue
        seen.add(name)
        if name == "__all__":
            continue
        if skip_private and _is_private(name):
            continue
        if name not in module.members:
            continue
        raw = module.members[name]
        # Without __all__, only document objects defined in this module (skip imports).
        if not use_exports and getattr(raw, "is_imported", False):
            continue
        member = _unwrap(raw)
        # Skip submodule objects when documenting a package's public API
        if member.kind == ObjectKind.MODULE:
            continue
        yield name, member


def render_object(
    obj: griffe.Object,
    *,
    display_name: str,
    heading_level: int,
    skip_private: bool,
    nested: bool = False,
) -> list[str]:
    obj = _unwrap(obj)
    parts: list[str] = []
    kind = obj.kind
    heading = f"{'#' * heading_level} `{display_name}`"
    if kind == ObjectKind.CLASS:
        heading = f"{'#' * heading_level} class `{display_name}`"
    elif kind == ObjectKind.FUNCTION:
        heading = f"{'#' * heading_level} `{display_name}()`"
    parts.append(heading)
    parts.append("")

    sig = format_signature(obj, display_name)
    if sig:
        parts.append("```python")
        parts.append(sig)
        parts.append("```")
        parts.append("")

    parts.extend(render_docstring(obj))

    if kind == ObjectKind.CLASS and not nested:
        for child_name, child in _iter_class_members(obj, skip_private):
            parts.extend(
                render_object(
                    child,
                    display_name=f"{display_name}.{child_name}",
                    heading_level=heading_level + 1,
                    skip_private=skip_private,
                    nested=True,
                )
            )

    if parts and parts[-1] != "":
        parts.append("")
    return parts


def _iter_class_members(
    cls: griffe.Object,
    skip_private: bool,
) -> Iterable[tuple[str, griffe.Object]]:
    for name, member in cls.members.items():
        if name in {"__init__", "__post_init__"}:
            continue
        if skip_private and _is_private(name):
            continue
        member = _unwrap(member)
        if member.kind not in {ObjectKind.FUNCTION, ObjectKind.ATTRIBUTE}:
            continue
        # Skip inherited / imported noise that is just a re-export alias without docs
        if member.kind == ObjectKind.ATTRIBUTE and not member.docstring:
            # Still document annotated public attributes with no docstring briefly
            if member.annotation is None:
                continue
        yield name, member


def format_signature(obj: griffe.Object, display_name: str) -> str | None:
    obj = _unwrap(obj)
    if obj.kind == ObjectKind.CLASS:
        init = obj.members.get("__init__")
        if init is None:
            return f"class {display_name}"
        init = _unwrap(init)
        params = _format_params(init.parameters, skip_self=True)
        return f"class {display_name}({params})"
    if obj.kind == ObjectKind.FUNCTION:
        params = _format_params(obj.parameters, skip_self=True)
        ret = f" -> {obj.returns}" if obj.returns else ""
        async_prefix = "async " if getattr(obj, "is_async", False) else ""
        return f"{async_prefix}def {display_name}({params}){ret}"
    if obj.kind == ObjectKind.ATTRIBUTE:
        ann = f": {obj.annotation}" if obj.annotation else ""
        default = ""
        if obj.value is not None:
            default = f" = {obj.value}"
        return f"{display_name}{ann}{default}"
    return None


def _format_params(parameters: Sequence[Any] | None, *, skip_self: bool) -> str:
    if not parameters:
        return ""
    parts: list[str] = []
    for param in parameters:
        name = param.name
        if skip_self and name in {"self", "cls"}:
            continue
        kind = param.kind
        if kind == ParameterKind.var_positional:
            rendered = f"*{name}"
        elif kind == ParameterKind.var_keyword:
            rendered = f"**{name}"
        else:
            rendered = name
            if param.annotation is not None:
                rendered = f"{rendered}: {param.annotation}"
            if param.default is not None:
                rendered = f"{rendered} = {param.default}"
        parts.append(rendered)
    return ", ".join(parts)


def render_docstring(obj: griffe.Object) -> list[str]:
    doc = obj.docstring
    if doc is None or not doc.value:
        return []

    parts: list[str] = []
    try:
        sections = doc.parsed
    except Exception:  # noqa: BLE001
        parts.append(_mdx_escape_prose(doc.value.strip()))
        parts.append("")
        return parts

    for section in sections:
        kind = section.kind
        if kind == DocstringSectionKind.text:
            text = _mdx_escape_prose(str(section.value).strip())
            if text:
                parts.append(text)
                parts.append("")
        elif kind == DocstringSectionKind.parameters:
            parts.append("**Parameters**")
            parts.append("")
            for item in section.value:
                ann = f" (`{item.annotation}`)" if item.annotation else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- `{item.name}`{ann}: {desc}" if desc else f"- `{item.name}`{ann}")
            parts.append("")
        elif kind == DocstringSectionKind.other_parameters:
            parts.append("**Other parameters**")
            parts.append("")
            for item in section.value:
                ann = f" (`{item.annotation}`)" if item.annotation else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- `{item.name}`{ann}: {desc}" if desc else f"- `{item.name}`{ann}")
            parts.append("")
        elif kind == DocstringSectionKind.returns:
            parts.append("**Returns**")
            parts.append("")
            for item in section.value:
                ann = f"`{item.annotation}`" if item.annotation else ""
                name = f"**{item.name}** " if getattr(item, "name", None) else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                line = "- "
                if name:
                    line += name
                if ann:
                    line += f"{ann}: " if desc else ann
                if desc:
                    line += desc if line.endswith(": ") or line == "- " else f" — {desc}"
                parts.append(line.rstrip(": "))
            parts.append("")
        elif kind == DocstringSectionKind.yields:
            parts.append("**Yields**")
            parts.append("")
            for item in section.value:
                ann = f"`{item.annotation}`" if item.annotation else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- {ann}: {desc}" if ann and desc else f"- {ann or desc}")
            parts.append("")
        elif kind == DocstringSectionKind.raises:
            parts.append("**Raises**")
            parts.append("")
            for item in section.value:
                ann = f"`{item.annotation}`" if item.annotation else "`Exception`"
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- {ann}: {desc}" if desc else f"- {ann}")
            parts.append("")
        elif kind == DocstringSectionKind.warns:
            parts.append("**Warns**")
            parts.append("")
            for item in section.value:
                ann = f"`{item.annotation}`" if item.annotation else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- {ann}: {desc}" if ann and desc else f"- {desc}")
            parts.append("")
        elif kind == DocstringSectionKind.examples:
            parts.append("**Examples**")
            parts.append("")
            for example_kind, value in section.value:
                if example_kind == DocstringSectionKind.examples or example_kind.value == "examples":
                    parts.append("```python")
                    parts.append(str(value).rstrip())
                    parts.append("```")
                    parts.append("")
                else:
                    text = _mdx_escape_prose(str(value).strip())
                    if text:
                        parts.append(text)
                        parts.append("")
        elif kind == DocstringSectionKind.attributes:
            parts.append("**Attributes**")
            parts.append("")
            for item in section.value:
                ann = f" (`{item.annotation}`)" if item.annotation else ""
                desc = _mdx_escape_prose((item.description or "").strip())
                parts.append(f"- `{item.name}`{ann}: {desc}" if desc else f"- `{item.name}`{ann}")
            parts.append("")
        elif kind == DocstringSectionKind.admonition:
            title = section.title or getattr(section.value, "kind", None) or "Note"
            contents = getattr(section.value, "contents", None) or str(section.value)
            parts.append(f"**{str(title).capitalize()}**")
            parts.append("")
            parts.append(_mdx_escape_prose(str(contents).strip()))
            parts.append("")
        elif kind == DocstringSectionKind.deprecated:
            parts.append(f"**Deprecated:** {_mdx_escape_prose(str(section.value))}")
            parts.append("")
        else:
            # Fallback: string-ify unknown sections
            value = getattr(section, "value", None)
            if value:
                parts.append(_mdx_escape_prose(str(value).strip()))
                parts.append("")

    return parts


def _unwrap(obj: griffe.Object) -> griffe.Object:
    current = obj
    seen: set[int] = set()
    while getattr(current, "is_alias", False):
        ident = id(current)
        if ident in seen:
            break
        seen.add(ident)
        try:
            current = current.target  # type: ignore[attr-defined]
        except Exception:  # noqa: BLE001
            break
    return current


def _is_private(name: str) -> bool:
    return name.startswith("_")


def _first_paragraph(text: str) -> str:
    chunks = text.strip().split("\n\n")
    return chunks[0].strip() if chunks else ""


def _yaml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


# Inline code spans (keep contents as-is; MDX still parses < and { outside them).
_INLINE_CODE_RE = re.compile(r"(``.*?``|`[^`\n]*`)")


def _mdx_escape_prose(text: str) -> str:
    """Escape MDX/JSX-significant chars in prose (not inside inline code).

    MDX treats ``<`` as JSX, so docstring text like ``<->`` or ``<=`` must
    become ``&lt;-&gt;`` / ``&lt;=``. Bare ``{`` / ``}`` are expression delimiters.
    """
    if not text:
        return text
    parts: list[str] = []
    for i, chunk in enumerate(_INLINE_CODE_RE.split(text)):
        if i % 2 == 1:
            parts.append(chunk)
            continue
        # Escape braces before `<` so replacement tokens stay intact.
        chunk = chunk.replace("{", "\0OB\0").replace("}", "\0CB\0")
        chunk = chunk.replace("\0OB\0", "{'{'}").replace("\0CB\0", "{'}'}")
        chunk = chunk.replace("<", "&lt;")
        parts.append(chunk)
    return "".join(parts)


if __name__ == "__main__":
    raise SystemExit(main())
